### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by ok2ju** [Atsman/osx-automation#2]
Could you complete readme to provide information about how to setup and run this? Btw, nice idea

**Comment by alehatsman** [comment]
Yo, basically you can run it from your machine, but u will need python and ansible already installed or u can initiate provisioning remotely, connecting it via ssh from another machine. 

I use it daily and each time I install something I do it by updating it in ansible first.

**Comment by ok2ju** [comment]
ty, I wrote tests for roles (using ansible molecule) but for another purpose and project. Is there any method to write tests for this roles? I mean I know how to write tests, but idk how to force molecule to run on vbox macos machine. Did you work with that?

**Comment by alehatsman** [comment]
No, I don't really care about tests here. I test it locally :)

In general, it should work in the same way like with Linux. If u have a VM with OSX, then point to it and run a test suite. But I guess it is not really easy to get OSX image without a licence problem etc.
